### ISSUE TITLE
BITGEt

### ISSUE THREAD

**Issue by Aomer97** [BitgetLimited/proof-of-reserves#15]

**Comment by Alfred360607** [comment]
It’s my account send my assets to my wallet address 

bc1q54s3gvauxdpwlwrvhda6s9pqmqarlfe9edt9t9

**Comment by SamyDgz** [comment]
![Screenshot_20240429-055754](https://github.com/BitgetLimited/proof-of-reserves/assets/168146136/9765583e-777f-4800-9523-cfa1f408fe71)
